GET http://localhost:5000/movies/

###
POST http://localhost:5000/movies/
Content-Type:application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}

###
GET http://localhost:5000/movies/54/
###

PUT http://localhost:5000/movies/54/
Content-Type:application/json

{
  "directorId": 24,
  "movieName": "Thore",
  "leadActor": "Christopher Hemsworth"
}
###
DELETE http://localhost:5000/movies/24/
###
GET http://localhost:5000/directors/
###
GET http://localhost:5000/directors/2/movies/